### PR TITLE
Add an auto refresh interval of 50ms to loadkeys and decrypt messages

### PR DESCRIPTION
**Pull request by kadogo**
In my last test the userscript didn't refresh when the url change.

The only way I find to make it work is using an interval check, I tried few other method with event listener but it didn't worked.

### CODE REVIEW

**Comment by mpgn** [comment]
Fix using this commit: https://github.com/mpgn/discord-e2e-encryption/commit/1d0d370c7b66745b9b41044ffd1ecda50a473d66

Can you check if this is working for you ?

**Comment by kadogo** [comment]
I took the userscript from https://raw.githubusercontent.com/mpgn/discord-e2e-encryption/1d0d370c7b66745b9b41044ffd1ecda50a473d66/discord-e2e.js and tried to change channels in the demo E2E server but it didn't worked for me (only when I refresh at first).

I will try again later with a clean profile without all my extension

**Comment by mpgn** [comment]
And using this one: https://github.com/mpgn/discord-e2e-encryption/commit/190dfc55f7e329745bb60995005491a99046fb11 ?

**Comment by kadogo** [comment]
It work this time, I felt some kind of latence but after a reload of my window it worked correctly

**Comment by mpgn** [comment]
it's not the best best solution, let's say a quick fix :)

**Pull request closed without merging**
